### PR TITLE
Fixed listFiles() is listing only first 100 files

### LINKED ISSUE #292: hosting.listFiles() is listing only first 100 files
**Describe the bug**
@syncano/core lib listing only first 100 files (`hosting.listFiles()`)

**To Reproduce**
1. Add more than 100 files to hosting (sync it)
2. Execute `hosting.listFiles()` using core library
3. Check number of files

**Expected behavior**
List should contain all the files.

### PR DESCRIPTION
**Pull request by ksyhoo**
[wip]

Resolves #292 

Tested locally but feedback would be much appreciated

### CODE REVIEW

File: packages/lib-js-core/src/hosting.js [hunk 1]
```diff
@@ -38,20 +39,42 @@ export default class Hosting extends QueryBuilder {
...
-        .then(resp => {
-          resolve(resp.objects)
-        })
-        .catch(reject)
+      resolve(results)
+      .catch(reject)
     })
   }
 
+  async fetchNextListFiles(hasNext, results){
```
Comment (mkucharz) [inline packages/lib-js-core/src/hosting.js]: Missing space before `{`.

File: packages/lib-js-core/src/hosting.js [hunk 2]
```diff
@@ -38,20 +39,42 @@ export default class Hosting extends QueryBuilder {
...
+      const nextParams = querystring.parse(hasNext.replace(/.*\?/, ''))
+      const q = querystring.stringify(...nextParams)
+      const next = nextParams.replace(/\?.*/, '');
+      const url = `${this.baseUrl}${next}?${q}`
+      const nextFetch = await this.fetch(url, {}, headers)
+      await this.fetchNextListFiles(nextFetch.next, results)
+
+    return results.concat(nextFetch.objects.slice(0))
+    }
+    else {
```
Comment (mkucharz) [inline packages/lib-js-core/src/hosting.js]: You don't need this `else` here because you have `return` above.

File: packages/lib-js-core/src/hosting.js [hunk 3]
```diff
@@ -38,20 +39,42 @@ export default class Hosting extends QueryBuilder {
...
 
-  listFiles (hostingId) {
+  async listFiles (hostingId) {
     debug('listFiles')
+    const headers = {
+      'X-API-KEY': this.instance.accountKey
+    }
+    let results = []
+    const initialFetch = await this.fetch(this.urlFiles(hostingId), {}, headers)
+    const hasNext = initialFetch.next;
```
Comment (mkucharz) [inline packages/lib-js-core/src/hosting.js]: Check this one: https://github.com/Syncano/syncano-node/blob/3caaaeb7fd29ddc8f6ee643babf93e2936c89e1a/packages/lib-js-core/src/data.js#L159

It is very similar, try to use same variable names and constructions.

**Comment by mkucharz** [comment]
Please add unit test for this case.

File: packages/lib-js-core/src/hosting.js [hunk 4]
```diff
@@ -41,37 +40,39 @@ export default class Hosting extends QueryBuilder {
 
   async listFiles (hostingId) {
     debug('listFiles')
-    const headers = {
-      'X-API-KEY': this.instance.accountKey
+    try {
```
Comment (mkucharz) [inline packages/lib-js-core/src/hosting.js]: i think it is obsolete. You are catching err to throw err. This is async operation just return `this.request` you don't even need await here.

File: packages/lib-js-core/src/hosting.js [hunk 5]
```diff
@@ -41,37 +40,39 @@ export default class Hosting extends QueryBuilder {
...
+  async loadNextPage (response , objects) {
+    debug('loadNextPage')
+    let hasNextPageMeta = response.next
+    try {
+      if (hasNextPageMeta) {
+        const nextObjects =  await this.request(`${this.baseUrl}${hasNextPageMeta}`)
+        return objects.concat(nextObjects)
+      }
+    return objects
+    } catch(err) {
```
Comment (mkucharz) [inline packages/lib-js-core/src/hosting.js]: Style.

File: packages/lib-js-core/src/hosting.js [hunk 6]
```diff
@@ -41,37 +40,39 @@ export default class Hosting extends QueryBuilder {
...
+      throw err
```
Comment (mkucharz) [inline packages/lib-js-core/src/hosting.js]: Same thing as above regarding the error handling.

File: packages/lib-js-core/src/hosting.js [hunk 7]
```diff
@@ -41,37 +40,39 @@ export default class Hosting extends QueryBuilder {
...
-      const nextFetch = await this.fetch(url, {}, headers)
-      await this.fetchNextListFiles(nextFetch.next, results)
-
-    return results.concat(nextFetch.objects.slice(0))
+    try {
+      let result = await this.fetch(url, {}, headers)
+      let objects = result.objects
+      objects = await this.loadNextPage(result, objects)
+      return objects
+    } catch (err) {
```
Comment (mkucharz) [inline packages/lib-js-core/src/hosting.js]: Same thing as above regarding the error handling.

File: packages/lib-js-core/test/unit/hosting.js [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+
+      const fourth100 = objects.slice(300, 302)
+      api
+        .get(`/v2/instances/${instanceName}/hosting/${hostingId}/files/?direction=1&last_pk=${third100last}`)
+        .reply(200, {
+          objects: fourth100,
+          next: null
+        })
+        return hosting
+        .listFiles(hostingId)
```
Comment (mkucharz) [inline packages/lib-js-core/test/unit/hosting.js]: Wrong indent.
