### PR TITLE
Fix for uploading src files / Add .syncanoignore 

### LINKED ISSUE #128: Bug while deploying project with .json file in sources.
### Expected behaviour

Same response with jsonValue from socket every time when importing json in js source code.

```
HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 19
Connection: keep-alive
Keep-Alive: timeout=20
Date: Mon, 05 Feb 2018 09:54:53 GMT

{"key":"jsonValue"}
```

### Actual behaviour

Every second deploy socket returns

```
HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 22
Connection: keep-alive
Keep-Alive: timeout=20
Date: Mon, 05 Feb 2018 09:54:21 GMT

{"key":"defaultValue"}
```
which is the default value in case of an import error

This is completly reporoducible, on first deploy you get {"key":"jsonValue"}, on second {"key":"defaultValue"}, on third again {"key":"jsonValue"} and fourth {"key":"defaultValue"}, and so on and on.

### Steps to reproduce

Create socket with socket.yaml, src/bug.js, and src/abc.json

socket.yaml:
```yaml
name: bug
description: Description of bug
version: 0.0.1
endpoints:
  bug:
    file: bug.js
```

src/bug.js:
```javascript
import Server from 'syncano-server';

export default ctx => {
  const server = Server(ctx);
  let dict;
  console.log('a');
  try {
    dict = require('./abc.json');
  } catch (e) {
    if (e.message && e.message.match(/^Cannot find module/) !== null) {
      dict = {key: 'defaultValue'};
    } else {
      throw e;
    }
  }
  return server.response.json(dict);
};
```

src/abc.json:
```javascript
{
  "key": "jsonValue"
}
```

I've just editted that "console.log('a')" line back and forward so that checksum test fails and socket is updated.

### Details

npx s version:
```
0.53.0
```

npx s hot logs attached as file
[out.log](https://github.com/Syncano/syncano-node/files/1694678/out.log)

Just to give a little context what I've used that for, it was a simple translation mapping for values returned from external service and depending on socket's language I was importing `${lang}.json`. That is for example en.json, no.json, pl.json etc etc. The key set to translate was very small so this solution seemed to be the quickest but I have to deploy things twice now on each socket edit.

### PR DESCRIPTION
**Pull request by mkucharz**
Fix #128 

Adding `.syncanoignore` support in `src` folder.

### CODE REVIEW

File: packages/cli/src/utils/sockets/sockets.js [hunk 1]
```diff
@@ -717,46 +698,39 @@ class Socket {
...
-      findFiles.on('data', (file) => {
+      files.forEach(file => {
         // with "internal" path
-        const fileNameWithPath = file.fullPath.replace(`${this.getSrcFolder()}`, '')
-        debug(`Adding file to archive: ${fileNameWithPath}`)
-        archive.file(file.fullPath, { name: fileNameWithPath })
+        const fileNameWithPath = file.replace(`${this.getCompiledScriptsFolder()}`, '')
+        const remoteFile = this.remote.files ? this.remote.files[fileNameWithPath] : null
+
+        if (remoteFile) {
```
Comment (adamwardecki) [inline packages/cli/src/utils/sockets/sockets.js]: Would this do the trick?:
```
if (!remoteFile || (remoteFile && remoteFile.checksum !== md5(fs.readFileSync(file)))) {
  archive.file(file, { name: fileNameWithPath })
}
```

File: packages/cli/src/utils/sockets/sockets.js [hunk 2]
```diff
@@ -717,46 +698,39 @@ class Socket {
         debug('Ignoring file: socket.yml')
       }
 
+      // Ignore patterns from .syncanoignore file
+      let ignore = []
+      try {
+        ignore = fs.readFileSync(`${this.getCompiledScriptsFolder()}/.syncanoignore`, 'utf8').split('\n')
+      } catch (err) {}
```
Comment (adamwardecki) [inline packages/cli/src/utils/sockets/sockets.js]: maybe a debug log could go into the catch clause

File: packages/cli/src/utils/sockets/sockets.js [hunk 3]
```diff
@@ -717,46 +698,39 @@ class Socket {
...
+      })
+
       // Adding all files (besides those filtered out)
-      findFiles.on('data', (file) => {
+      files.forEach(file => {
         // with "internal" path
-        const fileNameWithPath = file.fullPath.replace(`${this.getSrcFolder()}`, '')
-        debug(`Adding file to archive: ${fileNameWithPath}`)
-        archive.file(file.fullPath, { name: fileNameWithPath })
+        const fileNameWithPath = file.replace(`${this.getCompiledScriptsFolder()}`, '')
```
Comment (adamwardecki) [inline packages/cli/src/utils/sockets/sockets.js]: the `getCompiledScriptsFolder` is used 3 times in the `createZip` function.
